### ISSUE TITLE
RM: NullPointerException when `derived_from` is not specified

### ISSUE THREAD

**Issue by spresser-hlrs** [SODALITE-EU/ide#137]
When an RM is specified that does not include `derived_from`, the IDE generates a NullPointerException on the error console, rather than a useful error message:

```
java.lang.NullPointerException
	at org.sodalite.dsl.generator.RMGenerator.compile(RMGenerator.java:2692)
	at org.sodalite.dsl.generator.RMGenerator.compileRM(RMGenerator.java:348)
	at org.sodalite.dsl.generator.RMGenerator.doGenerate(RMGenerator.java:180)
	at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:44)
	at org.eclipse.xtext.generator.GeneratorDelegate.generate(GeneratorDelegate.java:35)
	at org.eclipse.xtext.builder.BuilderParticipant.handleChangedContents(BuilderParticipant.java:597)
	at org.eclipse.xtext.builder.BuilderParticipant.handleChangedContents(BuilderParticipant.java:578)
	at org.eclipse.xtext.builder.BuilderParticipant.doGenerate(BuilderParticipant.java:563)
	at org.eclipse.xtext.builder.BuilderParticipant.doBuild(BuilderParticipant.java:303)
	at org.eclipse.xtext.builder.BuilderParticipant.build(BuilderParticipant.java:265)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:162)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:70)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:392)
	at org.eclipse.xtext.builder.impl.XtextBuilder.addInfosFromTaskAndBuild(XtextBuilder.java:322)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:303)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:208)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

An example RM that generates this behavior is:
```
module: clinical

node_types:
	sodalite.nodes.RemoteNode:
		properties:
			remote_workspace:
				type: string
				description: "Directory to use on the remote server"
				required: true
		requirements:
			remote_address:
				capability: tosca.capabilities.Compute 
				relationship: tosca.relationships.DependsOn
```

**Comment by jesus-gorronogoitia** [comment]
fixed in commit https://github.com/SODALITE-EU/ide/commit/6f9d7a36502f7323ffd5dad756a9845efb86aae5
derived_from is not mandatory, so not required in TTL serialization, therefore this exception won't be triggered
I will prepare a new IDE update site so you can update your IDE

**Comment by jesus-gorronogoitia** [comment]
update site ready

**Comment by jesus-gorronogoitia** [comment]
@spresser-hlrs can this issue be closed?

**Comment by spresser-hlrs** [comment]
Yes, thank you! I just was able to test this and it no longer generates the error.
