### ISSUE TITLE
Creating a new AADM file fails

### ISSUE THREAD

**Issue by pmundt** [SODALITE-EU/ide#19]
Now that I have the components installed, I've tried to create a new project and add an AADM file to it. This has resulted in the following exception:

```
Sodalite backend configured with [KB Reasoner API: http://160.40.52.200:8084/reasoner-api/v0.6/, IaC API: http://160.40.52.200:8084/reasoner-api/v0.6/, xOpera http://160.40.52.200:8084/reasoner-api/v0.6/
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:445)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:352)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1033)
	at org.sodalite.dsl.ui.wizards.NewAADMWizard.performFinish(NewAADMWizard.java:117)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:832)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:472)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5685)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4953)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4446)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.handlers.WizardHandler$New.executeHandler(WizardHandler.java:260)
	at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:280)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)
	at org.eclipse.ui.internal.actions.CommandAction.runWithEvent(CommandAction.java:142)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5685)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4953)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4446)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1158)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1047)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
Caused by: java.util.NoSuchElementException
	at java.util.TreeMap.key(TreeMap.java:1327)
	at java.util.TreeMap.firstKey(TreeMap.java:290)
	at org.sodalite.dsl.ui.wizards.NewAADMWizard$1.run(NewAADMWizard.java:129)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:436)
	... 62 more
```

I verified with telnet that the host and port are reachable, so that's not the issue.

**Comment by jesus-gorronogoitia** [comment]
Hi @pmundt Thanks for reporting. It is not a development issue, but a incomplete deployment, as I did not include the Visual editor plugin in the IDE bundle to be installed from the Eclipse update site, so I am not facing this problem, but your are. I will fix this and inform you so you can build the update site again and update your installation.

**Comment by jesus-gorronogoitia** [comment]
Hi @pmundt Fixed, please pull the repo, build the update site, update the IDE plugins from the update site and try again to create a AADM model. I've detected a bug in the visualization of the AADM component types I cannot reproduce in my development environment. I am investigating

**Comment by pmundt** [comment]
I've tried this, and now during the update I hit this:

```
Your original request has been modified.
  "Optimization Editor" is already installed, so an update will be performed instead.
  "RM Editor" is already installed, so an update will be performed instead.
  "AADM Editor" is already installed, so an update will be performed instead.
Cannot complete the install because one or more required items could not be found.
  Software being installed: AADM Editor 1.0.0.202006190827 (org.sodalite.dsl.AADM.feature.feature.group 1.0.0.202006190827)
  Missing requirement: org.sodalite.dsl.AADM.design 1.0.0.202006190827 (org.sodalite.dsl.AADM.design 1.0.0.202006190827) requires 'osgi.bundle; com.altran.general.integration.xtextsirius.runtime 0.18.0' but it could not be found
  Cannot satisfy dependency:
    From: AADM Editor 1.0.0.202006190827 (org.sodalite.dsl.AADM.feature.feature.group 1.0.0.202006190827)
    To: org.eclipse.equinox.p2.iu; org.sodalite.dsl.AADM.design [1.0.0.202006190827,1.0.0.202006190827]
```

**Comment by jesus-gorronogoitia** [comment]
Please, add this update site to your Eclipse list of software sites:
`https://altran-mde.github.io/xtext-sirius-integration.io/p2/`
And check the checkbox _Contact all updates sites during install to find required software._ 
I will update the online documentation accordingly

**Comment by pmundt** [comment]
Thanks, that seems to have done the trick. It's all up and running now!
