### ISSUE TITLE
AADM save to KB results in invalid thread access

### ISSUE THREAD

**Issue by pmundt** [SODALITE-EU/ide#87]
When I try to save my AADM to the KB, I get an `invalid thread access` exception:

```
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4723)
	at org.eclipse.swt.SWT.error(SWT.java:4638)
	at org.eclipse.swt.SWT.error(SWT.java:4609)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:550)
	at org.eclipse.swt.widgets.Shell.<init>(Shell.java:272)
	at org.eclipse.swt.widgets.Shell.<init>(Shell.java:369)
	at org.eclipse.jface.window.Window.createShell(Window.java:487)
	at org.eclipse.jface.window.Window.create(Window.java:430)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:394)
	at org.eclipse.jface.dialogs.MessageDialog.openError(MessageDialog.java:480)
	at org.sodalite.dsl.ui.backend.RMBackendProxy.raiseConfigurationIssue(RMBackendProxy.java:148)
	at org.sodalite.dsl.ui.backend.RMBackendProxy.getKBReasoner(RMBackendProxy.java:124)
	at org.sodalite.dsl.ui.backend.AADMBackendProxy.lambda$0(AADMBackendProxy.java:161)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

The AADM is:

```
module: vehicleiot

import: kube

node_templates:

  kube-master-remote-vm:
    type: kube/sodalite.nodes.Kubernetes.Cluster
    properties:
      kubeconfig: "~/.kube/config"
    attributes:
      public_address: "192.168.2.19" // not quite public
      username: "centos"
        
  edgetpu-exporter-deployment-via-helm:
    type: sodalite.nodes.Kubernetes.Definition.Helm
    properties:
      name: "edgetpu-exporter-release-1-from-helm"
      namespace: "default"
      chart: "adaptant/edgetpu-exporter"
      chart_version: "latest"
      repo_name: "adaptant"
      repo_url: "https://adaptant-labs.github.io/charts/adaptant"
      keep_repo: true
    requirements:
      host:
        node: kube/kube-master-remote-vm
        
  ncs2-exporter-deployment-via-helm:
    type: sodalite.nodes.Kubernetes.Definition.Helm
    properties:
      name: "ncs2-exporter-release-1-from-helm"
      namespace: "default"
      chart: "adaptant/ncs2-exporter"
      chart_version: "latest"
      repo_name: "adaptant"
      repo_url: "https://adaptant-labs.github.io/charts/adaptant"
      keep_repo: false
    requirements:
      host:
        node: kube/kube-master-remote-vm
```

**Comment by jesus-gorronogoitia** [comment]
Fixed in commit https://github.com/SODALITE-EU/ide/commit/abbb8871b893a4bd73a7b6ca3e85fbf89a774c26
